version: '3.9'
services:

  bbl-db-postgres:
    image: postgres
    container_name: bbl-db-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bblPostgres
      - TZ=Europe/Moscow
    volumes:
      - ./data/bbl-db-postgres/:/var/lib/postgresql/data

  bbl-db-neo4j:
    image: neo4j
    container_name: bbl-db-neo4j
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - TZ=Europe/Moscow
    volumes:
      - ./data/bbl-db-neo4j/data:/data
      - ./data/bbl-db-neo4j/logs:/logs
      - ./data/bbl-db-neo4j/import:/var/lib/neo4j/import
      - ./data/bbl-db-neo4j/plugins:/plugins
      - ./data/bbl-db-neo4j/conf/:/conf/

  bbl-alpine:
    image: alpine
    container_name: bbl-alpine
    command: sh
    tty: true

#  bbl-bitcoin:
#    container_name: bbl-bitcoind
#    user: 1000:1000
#    image: lncm/bitcoind:v25.1-arm64v8-build49
#    volumes:
#      - ./data/bbl-bitcoin/bitcoin:/data/.bitcoin
#    restart: on-failure
#    stop_grace_period: 15m30s
#    ports:
#      - "8333:8333"
#      - "8332:8332"
#      - "28332:28332"
#      - "28333:28333"