--liquibase formatted sql

--changeset anaksenov:20230109-create-table-bitcoin_block_initial_data#001
CREATE TABLE if not exists public.bitcoin_block_initial_data (
    id bigint NOT NULL,
    hash character varying(64) UNIQUE,
    blockNumber int UNIQUE,
    status character varying(25),
    created_at timestamp,
    updated_at timestamp,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

ALTER TABLE public.bitcoin_block_initial_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bitcoin_block_initial_data_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

comment on table public.bitcoin_block_initial_data is 'Bitcoin block hash and number to use later in request full header and transactions';

--rollback drop table if exists public.bitcoin_block_initial_data;